//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirLineReservationSystemProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AirlineReservationEntities : DbContext
    {
        public AirlineReservationEntities()
            : base("name=AirlineReservationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_AircraftDetails> tbl_AircraftDetails { get; set; }
        public virtual DbSet<tbl_Airports> tbl_Airports { get; set; }
        public virtual DbSet<tbl_FlightDetails> tbl_FlightDetails { get; set; }
        public virtual DbSet<tblAdmin> tblAdmins { get; set; }
        public virtual DbSet<tblBooking> tblBookings { get; set; }
        public virtual DbSet<tblpassenger_table> tblpassenger_table { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
        public virtual DbSet<tblSeat> tblSeats { get; set; }
        public virtual DbSet<tblTicket_table> tblTicket_table { get; set; }
        public virtual DbSet<tblTrip> tblTrips { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
    
        public virtual ObjectResult<proc_DetailsConfirmation_Result> proc_DetailsConfirmation(string mBID)
        {
            var mBIDParameter = mBID != null ?
                new ObjectParameter("mBID", mBID) :
                new ObjectParameter("mBID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_DetailsConfirmation_Result>("proc_DetailsConfirmation", mBIDParameter);
        }
    
        public virtual int proc_UserRegisteration(string t, string f, string l, Nullable<System.DateTime> dob, string phone, string email, string pass)
        {
            var tParameter = t != null ?
                new ObjectParameter("t", t) :
                new ObjectParameter("t", typeof(string));
    
            var fParameter = f != null ?
                new ObjectParameter("f", f) :
                new ObjectParameter("f", typeof(string));
    
            var lParameter = l != null ?
                new ObjectParameter("l", l) :
                new ObjectParameter("l", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_UserRegisteration", tParameter, fParameter, lParameter, dobParameter, phoneParameter, emailParameter, passParameter);
        }
    
        public virtual ObjectResult<proc_UserLogin_Result> proc_UserLogin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_UserLogin_Result>("proc_UserLogin");
        }
    
        public virtual ObjectResult<proc_AdminLogin_Result> proc_AdminLogin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_AdminLogin_Result>("proc_AdminLogin");
        }
    }
}
